### PR TITLE
bug/LM-6229 Sending itinerary quote to email address shows as invalid

### PR DESCRIPTION
**Pull request by gumvic**
[LM-6229](https://locomote.atlassian.net/browse/LM-6229)

Let's update the email regex to a RFC 2822 compliant one -- https://gist.github.com/badsyntax/719800

It's not perfect still (see the comments for that gist),  but how critical is that?

### CODE REVIEW

**Review by justinTNT — APPROVED** [review]

**Comment by benkitzelman** [comment]
The biggest question is - how does this fit into our data flow? When is this validator actually used? Main reason I'm asking is cos IF we pull the email from a PNR - then some chars in the regex CANT be stored on the pnr - the GDS strips them out.

(cf: https://github.com/locomote/node-uprofile-orm/pull/44 - which fixed this issue, prevent TMP from exporting a GDS unsafe email to uprofile)

**Review by benkitzelman — APPROVED** [review]
I'll approve for now - but that question about PNR storage is worth considering..... If this is for an email that IS pulled from a pnr - I'd consider leaving your changes in AND adding a separate regex for GDS safe emails and validate in CBT using that

**Comment by gumvic** [comment]
@benkitzelman 
At this moment, this functionality is only used in CBT here -- https://github.com/locomote/cbt/blob/b1c6e2646acc4013276129ab7d454b0694d1765b/app/mailers/trip_share_mailer.js#L53, where it's safe to just validate without thinking about GDS.
Therefore, I'd propose to leave this as it is, and add a new card about adding the GDS email validation, too, and making `uprofile-orm` use this library.
What do you think?

**Comment by gumvic** [comment]
@benkitzelman 
Hi, based on our discussion I've created this tech debt card -- https://locomote.atlassian.net/browse/LM-6477

**Pull request merged**
